import { MenuCategory, MenuItem } from "./types";

export const DEFAULT_CATEGORIES: MenuCategory[] = [
  { id: "breakfast", name: "Breakfast Delights", slug: "breakfast", order: 1, description: "Continental and authentic Nigerian morning delicacies", icon: "Coffee", isActive: true },
  { id: "starters", name: "Starters & Small Bites", slug: "starters", order: 2, description: "Crispy appetizers, dips, and hot finger foods", icon: "Utensils", isActive: true },
  { id: "rice", name: "Rice Collection", slug: "rice", order: 3, description: "Signature smoky jollof, fried rice, and special bowls", icon: "Bowl", isActive: true },
  { id: "pasta", name: "Pasta & Noodles", slug: "pasta", order: 4, description: "Rich creamy and spicy pasta masterpieces", icon: "Soup", isActive: true },
  { id: "soups", name: "Soups & Swallows", slug: "soups", order: 5, description: "Traditional Nigerian soups paired with hot swallows", icon: "Flame", isActive: true },
  { id: "dips-sauces", name: "Dips & Sauces", slug: "dips-sauces", order: 6, description: "Flavorful side dips and gourmet sauces", icon: "Sparkles", isActive: true },
  { id: "local-favorites", name: "Local Favorites", slug: "local-favorites", order: 7, description: "Beloved homestyle porridges and native combinations", icon: "Heart", isActive: true },
  { id: "peppersoup", name: "Peppersoup Corner", slug: "peppersoup", order: 8, description: "Aromatic spicy herbal broths with fresh meats and fish", icon: "Flame", isActive: true },
  { id: "spicy", name: "Spicy Specialties", slug: "spicy", order: 9, description: "Fiery wok-tossed meats and snail specials", icon: "Pepper", isActive: true },
  { id: "grills", name: "Grills & Barbecue", slug: "grills", order: 10, description: "Flame-grilled poultry, whole fish, and authentic suya", icon: "Drumstick", isActive: true },
  { id: "fast-food", name: "Fast Food & Quick Meals", slug: "fast-food", order: 11, description: "Gourmet shawarma, loaded chips, and toasted sandwiches", icon: "Sandwich", isActive: true },
  { id: "platters", name: "Signature Platters", slug: "platters", order: 12, description: "Lavish sharing platters for celebration and groups", icon: "Crown", isActive: true },
  { id: "desserts", name: "Desserts & Fruits", slug: "desserts", order: 13, description: "Sweet indulgence, artisan cakes, and seasonal fruit platters", icon: "Cake", isActive: true },
  { id: "bar", name: "Bar & Wine", slug: "bar", order: 14, description: "Fine wines, chilled beers, and luxury spirits", icon: "Wine", isActive: true },
];

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  // BREAKFAST DELIGHTS - Continental
  {
    id: "bf-1",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Classic Pancake & Tea",
    description: "Fluffy golden buttermilk pancakes served with maple syrup, whipped butter, and freshly brewed English tea.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Sweet"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "15-20 mins",
    order: 1,
  },
  {
    id: "bf-2",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Sunrise Sausage & Scrambled Eggs",
    description: "Tender herb-seasoned sausages, creamy scrambled eggs, and warm buttered toast.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 2,
  },
  {
    id: "bf-3",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Golden Toast & Sardine Delight",
    description: "Crispy grilled sourdough toast topped with savory spiced sardine medley and fresh spring herbs.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&auto=format&fit=crop&q=80",
    dietary: ["Seafood"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 3,
  },
  {
    id: "bf-4",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Executive Breakfast Combo",
    description: "The complete hotel morning feast: eggs to order, beef sausage, baked beans, grilled tomato, toast, and choice of hot tea or fresh juice.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 4,
  },

  // BREAKFAST DELIGHTS - Nigerian
  {
    id: "bf-5",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Custard / Pap & Akara",
    description: "Silky hot vanilla custard or traditional fermented pap paired with fresh crispy golden bean cakes (akara).",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Halal"],
    isAvailable: true,
    preparationTime: "15-20 mins",
    order: 5,
  },
  {
    id: "bf-6",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Village Yam & Egg Sauce",
    description: "Boiled soft white yam slices served with rich garden egg-and-tomato pepper sauce.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 6,
  },
  {
    id: "bf-7",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Plantain Sunrise Special",
    description: "Sweet ripe plantain coins pan-seared to caramelized perfection, served with scrambled eggs and bell peppers.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 7,
  },
  {
    id: "bf-8",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Beans & Sweet Plantain Combo",
    description: "Slow-cooked honey beans stewed in palm oil and aromatics, served alongside golden dodo plantain.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 8,
  },
  {
    id: "bf-9",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "Moi Moi Delight",
    description: "Steamed savory bean pudding enriched with flaked fish, boiled eggs, and bell pepper emulsion.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Halal"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 9,
  },
  {
    id: "bf-10",
    categoryId: "breakfast",
    categoryName: "Breakfast Delights",
    title: "White Rice & Sausage Breakfast Bowl",
    description: "Fluffy steamed rice served with fried egg, sliced savory sausage, and house tomato gravy.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 10,
  },

  // STARTERS & SMALL BITES
  {
    id: "st-1",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Crispy Chicken Wings & Dip",
    description: "Golden fried chicken wings tossed in mild spices, served with signature garlic mayo dip.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1527477378408-1bc0a6498f3b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 1,
  },
  {
    id: "st-2",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Peppered Assorted Meat",
    description: "Bite-sized cuts of shaki, liver, beef, and round-about slow-braised and pan-fried with scotch bonnet peppers and onions.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "st-3",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Signature Asun",
    description: "Fiery fire-roasted goat meat cutlets stir-fried with habanero chili, sliced red onions, and traditional spices.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "st-4",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Special Nkwobi",
    description: "Tender spiced cow foot pieces bathed in rich palm oil potash sauce, utazi leaves, and aromatic ehuru seeds.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "25 mins",
    order: 4,
  },
  {
    id: "st-5",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Spicy Goat Meat Bites",
    description: "Tender boneless goat meat seasoned with indigenous suya rubs and sweet caramelized onion rings.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 5,
  },
  {
    id: "st-6",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Fish Fingers & Dip",
    description: "Crispy breaded white fish strips served golden brown with house tartar dip and lemon wedge.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&auto=format&fit=crop&q=80",
    dietary: ["Seafood"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 6,
  },
  {
    id: "st-7",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Mini Bread Pizza",
    description: "Oven-toasted French baguette slices baked with marinara sauce, mozzarella cheese, and bell pepper chunks.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "15-20 mins",
    order: 7,
  },
  {
    id: "st-8",
    categoryId: "starters",
    categoryName: "Starters & Small Bites",
    title: "Plantain Pizza Supreme",
    description: "Creative culinary treat using sweet baked plantain base loaded with cheese, spiced beef shreds, and fresh basil.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 8,
  },

  // RICE COLLECTION
  {
    id: "rc-1",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Banky Signature Jollof Rice",
    description: "Premium firewood-smoky long-grain rice infused with plum tomatoes, red peppers, and secret spices.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Spicy", "Halal"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 1,
  },
  {
    id: "rc-2",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Royal Fried Rice",
    description: "Wok-tossed rice with sweet corn, garden peas, carrots, diced liver, and aromatic curry herbs.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "rc-3",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Coconut Paradise Rice",
    description: "Fragrant rice simmered gently in pure pressed coconut milk, baby shrimp, and sweet peppers.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "20-25 mins",
    order: 3,
  },
  {
    id: "rc-4",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Oriental Delight Rice",
    description: "Asian-inspired stir-fry rice with sesame oil, spring scallions, bell peppers, and light soy glaze.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 4,
  },
  {
    id: "rc-5",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Chinese Special Rice",
    description: "Authentic high-heat wok Chinese fried rice with eggs, shredded chicken, and tender green beans.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "25 mins",
    order: 5,
  },
  {
    id: "rc-6",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Garden Vegetable Rice",
    description: "Healthy and vibrant rice cooked with seasonal farm-fresh vegetables and olive oil.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 6,
  },
  {
    id: "rc-7",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Creamy Curry Rice",
    description: "Velvety spiced curry-infused rice prepared with fragrant ginger, garlic, and rich coconut cream.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 7,
  },
  {
    id: "rc-8",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Fisherman’s Rice Bowl",
    description: "Rich seafood rice platter generously garnished with seasoned pan-seared fish cuts and prawns.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    dietary: ["Seafood", "Chef Special"],
    isAvailable: true,
    preparationTime: "25 mins",
    order: 8,
  },
  {
    id: "rc-9",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Asun Fiesta Rice",
    description: "Spicy smoky jollof rice tossed with tender roasted goat meat bites (asun) and caramelized onions.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 9,
  },
  {
    id: "rc-10",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Concoction Pot Rice",
    description: "Traditional village-style one-pot rice stewed with dry fish, crayfish, scent leaves, and authentic palm oil.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Spicy"],
    isAvailable: true,
    preparationTime: "25 mins",
    order: 10,
  },
  {
    id: "rc-11",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Rice & Beans Combo",
    description: "Classic Nigerian long-grain parboiled rice paired with stewed brown beans and pepper sauce.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 11,
  },
  {
    id: "rc-12",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Classic White Rice & Stew",
    description: "Steamed fluffy white rice served with deep-fried red bell pepper and tomato stew.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80",
    dietary: ["Halal"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 12,
  },
  {
    id: "rc-13",
    categoryId: "rice",
    categoryName: "Rice Collection",
    title: "Ofada Rice & Beans Combo",
    description: "Aromatic indigenous short-grain unpolished Ofada rice served with boiled beans and spicy ayamase sauce.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20-25 mins",
    order: 13,
  },

  // PASTA & NOODLES
  {
    id: "pa-1",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Banky Jollof Pasta",
    description: "Spaghetti simmered in rich Nigerian tomato-bell pepper reduction with aromatic thyme and herbs.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Spicy"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 1,
  },
  {
    id: "pa-2",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Creamy Alfredo Pasta",
    description: "Fettuccine pasta in a velvety garlic and parmesan cheese cream sauce with cracked black pepper.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "pa-3",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Spaghetti Bolognese",
    description: "Hearty Italian-style minced beef ragu slow-simmered with tomatoes, red wine reduction, and basil.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "pa-4",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Asun Spaghetti Supreme",
    description: "Spaghetti tossed with fiery diced asun goat meat, scotch bonnets, and sweet bell peppers.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 4,
  },
  {
    id: "pa-5",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Chef’s Special Spaghetti",
    description: "Stir-fried spaghetti loaded with shredded chicken, sweet corn, green peas, and hot pepper medley.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 5,
  },
  {
    id: "pa-6",
    categoryId: "pasta",
    categoryName: "Pasta & Noodles",
    title: "Noodles & Egg Delight",
    description: "Quick-wok noodles with carrots, green peppers, and choice of fried or poached egg.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 6,
  },

  // SOUPS & SWALLOWS - SWALLOWS
  {
    id: "sw-1",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Eba (Cassava Swallow)",
    description: "Freshly turned smooth golden or white garri swallow.",
    price: 1000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 1,
  },
  {
    id: "sw-2",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Semo Swallow",
    description: "Soft and light semolina swallow turned to silky perfection.",
    price: 1500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 2,
  },
  {
    id: "sw-3",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Whole Wheat Swallow",
    description: "Fiber-rich whole wheat meal prepared smooth and warm.",
    price: 1500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 3,
  },
  {
    id: "sw-4",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Traditional Fufu",
    description: "Fresh cassava fermented fufu prepared soft and smooth.",
    price: 1000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 4,
  },
  {
    id: "sw-5",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Fresh Pounded Yam (Iyan)",
    description: "Authentic Ekiti pounded yam made from freshly boiled tubers, light and stretchy.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "15 mins",
    order: 5,
  },
  {
    id: "sw-6",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Pando Yam Flour",
    description: "Instant processed poundo yam turned to velvety smooth swallow.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 6,
  },
  {
    id: "sw-7",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Plantain Swallow",
    description: "Nutritious green unripe plantain meal turned into an authentic fiber-rich swallow.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 7,
  },

  // SOUPS & SWALLOWS - SOUPS
  {
    id: "sp-1",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Edikang Ikong Supreme",
    description: "Iconic royal vegetable soup cooked with waterleaf, ugwu, periwinkles, dry fish, and stockfish.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "25 mins",
    order: 8,
  },
  {
    id: "sp-2",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Egusi Delight",
    description: "Rich ground melon seed soup stir-fried with palm oil, leafy greens, crayfish, and seasoning.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 9,
  },
  {
    id: "sp-3",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Rich Ogbono Soup",
    description: "Draw soup prepared with wild African bush mango seeds, stockfish chunks, and aromatic scent leaf.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 10,
  },
  {
    id: "sp-4",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Vegetable Harvest Soup (Efo Riro)",
    description: "Rich Yoruba vegetable soup rich with shaki, dried fish, locust beans (iru), and scotch bonnet pepper.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 11,
  },
  {
    id: "sp-5",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Okra Special Soup",
    description: "Freshly sliced crunchy okra simmered in seafood broth with dry prawns and pepper reduction.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Seafood"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 12,
  },
  {
    id: "sp-6",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Special Ewedu Soup Combo",
    description: "Smooth jute leaves whisked with potash and iru, served with gbegiri bean broth and pepper stew.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 13,
  },
  {
    id: "sp-7",
    categoryId: "soups",
    categoryName: "Soups & Swallows",
    title: "Special Egusi & Okra Soup Combo",
    description: "A harmonious combination of thick melon seed soup and fresh crunchy okra.",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 14,
  },

  // DIPS & SAUCES
  {
    id: "ds-1",
    categoryId: "dips-sauces",
    categoryName: "Dips & Sauces",
    title: "Gourmet Dip Collection (Mayo, Ranch, Chili, Honey Mustard, Garlic Yoghurt)",
    description: "Choice of Garlic Mayo, Creamy Ranch, Spicy Chili, Honey Mustard, or Creamy Garlic Yoghurt Dip.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian"],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 1,
  },
  {
    id: "ds-2",
    categoryId: "dips-sauces",
    categoryName: "Dips & Sauces",
    title: "Chef Turkey Sauce",
    description: "Savory simmered turkey gravy with sweet onions and bell peppers.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 2,
  },
  {
    id: "ds-3",
    categoryId: "dips-sauces",
    categoryName: "Dips & Sauces",
    title: "Chicken & Beef Sauces",
    description: "Choice of richly spiced chicken sauce or tender beef pepper reduction sauce.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 3,
  },
  {
    id: "ds-4",
    categoryId: "dips-sauces",
    categoryName: "Dips & Sauces",
    title: "Fish, Veg & Curry Sauce Selection",
    description: "Choice of pan-simmered fish sauce (₦2,500), vegetable garden sauce (₦2,000), or aromatic curry sauce (₦2,500).",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Halal"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 4,
  },

  // LOCAL FAVORITES
  {
    id: "lf-1",
    categoryId: "local-favorites",
    categoryName: "Local Favorites",
    title: "Plantain Porridge Special",
    description: "Slow-simmered green and half-ripe plantains cooked with smoked fish, scent leaves, and authentic palm oil.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    preparationTime: "20-25 mins",
    order: 1,
  },
  {
    id: "lf-2",
    categoryId: "local-favorites",
    categoryName: "Local Favorites",
    title: "Beans & Plantain Pot",
    description: "Rich Nigerian ewa aganyin style beans pot cooked with caramelized pepper stew and fried sweet plantain.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Gluten-Free"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "lf-3",
    categoryId: "local-favorites",
    categoryName: "Local Favorites",
    title: "Village Style Yam Porridge",
    description: "Tender white yam cubes stewed into creamy asaro with dried fish flakes, red palm oil, and greens.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "lf-4",
    categoryId: "local-favorites",
    categoryName: "Local Favorites",
    title: "Native Sauce & Plantain",
    description: "Golden fried dodo or boiled plantains served with spicy native palm oil and smoked fish relish.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 4,
  },

  // PEPPERSOUP CORNER
  {
    id: "ps-1",
    categoryId: "peppersoup",
    categoryName: "Peppersoup Corner",
    title: "Goat Meat Pepper Soup",
    description: "Hot aromatic broth infused with African spices, uda, uziza seeds, and tender cuts of goat meat.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Gluten-Free", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "20 mins",
    order: 1,
  },
  {
    id: "ps-2",
    categoryId: "peppersoup",
    categoryName: "Peppersoup Corner",
    title: "Chicken Pepper Soup",
    description: "Tender chicken steeped in piping-hot herbal pepper soup with scent leaves.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "ps-3",
    categoryId: "peppersoup",
    categoryName: "Peppersoup Corner",
    title: "Assorted Meat Pepper Soup",
    description: "Abundant assortment of liver, kidney, tripe, and beef simmered in hot spice broth.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Gluten-Free"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "ps-4",
    categoryId: "peppersoup",
    categoryName: "Peppersoup Corner",
    title: "Catfish Pepper Soup (Point & Kill)",
    description: "Fresh live catfish poached in spicy peppery broth with utazi leaves. Fresh and invigorating.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Seafood", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "25-30 mins",
    order: 4,
  },

  // SPICY SPECIALTIES
  {
    id: "spc-1",
    categoryId: "spicy",
    categoryName: "Spicy Specialties",
    title: "Pepper Goat Meat",
    description: "Crispy browned goat meat tossed in blazing habanero and red pepper reduction with sweet onions.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 1,
  },
  {
    id: "spc-2",
    categoryId: "spicy",
    categoryName: "Spicy Specialties",
    title: "Pepper Beef",
    description: "Tender beef fillets pan-fried and glazed in hot pepper sauce with bell pepper strips.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "spc-3",
    categoryId: "spicy",
    categoryName: "Spicy Specialties",
    title: "Pepper Turkey",
    description: "Meaty roasted turkey cutlets drenched in fiery pepper sauce with sweet onions.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1527477378408-1bc0a6498f3b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "spc-4",
    categoryId: "spicy",
    categoryName: "Spicy Specialties",
    title: "Pepper Chicken",
    description: "Golden fried chicken quarters coated in house fiery pepper sauce.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1527477378408-1bc0a6498f3b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 4,
  },
  {
    id: "spc-5",
    categoryId: "spicy",
    categoryName: "Spicy Specialties",
    title: "Pepper Snail",
    description: "Giant African land snails slow-cooked tender, tossed in scotch bonnet relish with fresh utazi.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "25 mins",
    order: 5,
  },

  // GRILLS & BARBECUE
  {
    id: "gr-1",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Banky Flame-Grilled Chicken",
    description: "Marinated overnight in secret Nigerian spices, flame-grilled to juicy perfection over wood charcoal.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special", "Halal"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "25 mins",
    order: 1,
  },
  {
    id: "gr-2",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Barbecue Turkey Delight",
    description: "Succulent turkey leg glazed in sweet-smoky barbecue sauce and flame-grilled.",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "25 mins",
    order: 2,
  },
  {
    id: "gr-3",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Suya-Spiced Beef",
    description: "Thin-sliced tender beef skewers dusted with northern yaji pepper, ground peanut rub, and red onions.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy", "Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 3,
  },
  {
    id: "gr-4",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Peppered Goat Meat (Barbecue)",
    description: "Charcoal-smoked goat meat cubes glazed with spicy herb butter.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    dietary: ["Spicy"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 4,
  },
  {
    id: "gr-5",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Whole Grilled Croaker Fish",
    description: "Fresh croaker fish scored, marinated in ginger and chili marinade, and charcoal-grilled with roasted plantains.",
    price: 7000,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80",
    dietary: ["Seafood", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "30-35 mins",
    order: 5,
  },
  {
    id: "gr-6",
    categoryId: "grills",
    categoryName: "Grills & Barbecue",
    title: "Whole Grilled Catfish",
    description: "Seasoned barbecue catfish grilled whole with peppers, served with spicy dip and lime.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    dietary: ["Seafood", "Chef Special"],
    isAvailable: true,
    preparationTime: "30-35 mins",
    order: 6,
  },

  // FAST FOOD & QUICK MEALS
  {
    id: "ff-1",
    categoryId: "fast-food",
    categoryName: "Fast Food & Quick Meals",
    title: "Chicken Shawarma",
    description: "Warm flatbread rolled with spiced shaved chicken, cabbage, sausages, and creamy garlic mayonnaise.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "15 mins",
    order: 1,
  },
  {
    id: "ff-2",
    categoryId: "fast-food",
    categoryName: "Fast Food & Quick Meals",
    title: "Chicken & Chips Supreme",
    description: "Golden crispy chicken served with hot potato chips, ketchup, and seasoned garlic mayo.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "20 mins",
    order: 2,
  },
  {
    id: "ff-3",
    categoryId: "fast-food",
    categoryName: "Fast Food & Quick Meals",
    title: "Triple-Decker Club Sandwich",
    description: "Toasted white bread layered with sliced chicken breast, boiled egg, cheese, lettuce, tomato, and fries.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 3,
  },
  {
    id: "ff-4",
    categoryId: "fast-food",
    categoryName: "Fast Food & Quick Meals",
    title: "Chicken Sandwich",
    description: "Freshly toasted sandwich with seasoned chicken spread, crisp cucumbers, and house dressing.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
    dietary: ["Halal"],
    isAvailable: true,
    preparationTime: "15 mins",
    order: 4,
  },

  // SIGNATURE PLATTERS
  {
    id: "plt-1",
    categoryId: "platters",
    categoryName: "Signature Platters",
    title: "Platter One (The Grand Feast)",
    description: "Lavish sharing platter: Fried rice, Smoky Jollof rice, Peppered chicken, Golden plantain sticks, Crisp apple salad, and Plantain pizza.",
    price: 20000,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
    dietary: ["Platter", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "30-40 mins",
    order: 1,
  },
  {
    id: "plt-2",
    categoryId: "platters",
    categoryName: "Signature Platters",
    title: "Platter Two (Surf & Turf Deluxe)",
    description: "Executive combination platter: Fisherman's rice, Succulent pepper turkey, Tender beef sticks, Garden fresh salad, and Apple berries medley.",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    dietary: ["Platter", "Chef Special", "Seafood"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "35-45 mins",
    order: 2,
  },
  {
    id: "plt-3",
    categoryId: "platters",
    categoryName: "Signature Platters",
    title: "Platter Three (The Royal Connoisseur)",
    description: "The ultimate luxury ensemble: Asun fried rice, Peppered beef, Asun spaghetti, Savory plantain pizza, and Fresh sliced sweet oranges.",
    price: 30000,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
    dietary: ["Platter", "Chef Special", "Spicy"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "40-45 mins",
    order: 3,
  },

  // DESSERTS
  {
    id: "des-1",
    categoryId: "desserts",
    categoryName: "Desserts & Fruits",
    title: "Artisan Ice Cream Trio",
    description: "Three generous scoops of premium vanilla, chocolate, and strawberry ice cream with wafer roll.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80",
    dietary: ["Sweet", "Vegetarian"],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 1,
  },
  {
    id: "des-2",
    categoryId: "desserts",
    categoryName: "Desserts & Fruits",
    title: "Fresh Tropical Fruit Platter",
    description: "Chilled watermelon, sweet pineapple wedges, papaya, and sweet grapes beautifully arranged.",
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian", "Sweet"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 2,
  },
  {
    id: "des-3",
    categoryId: "desserts",
    categoryName: "Desserts & Fruits",
    title: "Rich Chocolate Fudge Cake",
    description: "Decadent dark chocolate sponge layered with ganache and dusted with cocoa.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    dietary: ["Sweet", "Vegetarian"],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 3,
  },
  {
    id: "des-4",
    categoryId: "desserts",
    categoryName: "Desserts & Fruits",
    title: "New York Style Cheesecake",
    description: "Velvety baked cream cheese over buttery graham cracker crust with berry coulis drizzle.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80",
    dietary: ["Sweet", "Chef Special"],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 4,
  },
  {
    id: "des-5",
    categoryId: "desserts",
    categoryName: "Desserts & Fruits",
    title: "Fresh Fruit Salad Bowl",
    description: "Tossed diced seasonal fruits in light citrus syrup with fresh mint leaves.",
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=600&auto=format&fit=crop&q=80",
    dietary: ["Gluten-Free", "Vegetarian", "Sweet"],
    isAvailable: true,
    preparationTime: "10 mins",
    order: 5,
  },

  // BAR & WINE
  {
    id: "bar-1",
    categoryId: "bar",
    categoryName: "Bar & Wine",
    title: "Golenn Rossi Premium Wine",
    description: "A bottle of vintage Golenn Rossi, with rich bouquet, balanced tannins, and smooth finish.",
    price: 30000,
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
    preparationTime: "5 mins",
    order: 1,
  },
  {
    id: "bar-2",
    categoryId: "bar",
    categoryName: "Bar & Wine",
    title: "Banky Sunset Cocktail",
    description: "Our signature tropical cocktail with spiced rum, passion fruit puree, lime juice, and grenadine.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80",
    dietary: ["Chef Special"],
    isAvailable: true,
    preparationTime: "5-10 mins",
    order: 2,
  },
  {
    id: "bar-3",
    categoryId: "bar",
    categoryName: "Bar & Wine",
    title: "Virgin Chapman Mocktail",
    description: "Traditional Nigerian Chapman with Angostura bitters, Fanta, Sprite, cucumber, and orange slices.",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    dietary: ["Vegetarian", "Sweet"],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 3,
  },
  {
    id: "bar-4",
    categoryId: "bar",
    categoryName: "Bar & Wine",
    title: "Chilled Premium Beer Selection",
    description: "Ice-cold Heineken, Guinness Extra Stout, Budweiser, or Star Lager (bottle).",
    price: 2000,
    imageUrl: "https://images.unsplash.com/photo-1608270546103-97b7964b42b9?w=600&auto=format&fit=crop&q=80",
    dietary: [],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 4,
  },
  {
    id: "bar-5",
    categoryId: "bar",
    categoryName: "Bar & Wine",
    title: "Chilled Soft Drinks & Sparkling Water",
    description: "Coca-Cola, Sprite, Fanta, Schweppes Tonic, or bottled sparkling water.",
    price: 1000,
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    dietary: [],
    isAvailable: true,
    preparationTime: "5 mins",
    order: 5,
  }
];
